import type { Metadata } from "next";
import StyledComponentsRegistry from '../lib/registry'
import { GmarketSans } from "@/public/fonts/fonts";
import { Header } from "@/components/header/header";
import { Navigation } from "@/components/navigation/navigation";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={GmarketSans.className} suppressHydrationWarning>
      <body>
        <div className="body-wrapper">
          <StyledComponentsRegistry>
          <Header />
          {children}
          <Navigation />
          </StyledComponentsRegistry>
        </div>
      </body>
    </html>
  );
}
