import type { Metadata } from "next";
import { Header } from "@/components/header/header";
import { Geist, Geist_Mono } from "next/font/google";
import { GmarketSans } from "@/public/fonts/fonts";
import "./globals.css";
import { Navigation } from "@/components/navigation/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={GmarketSans.className} suppressHydrationWarning>
      <body>
        <div className="body-wrapper">
          <Header />
          {children}
          <Navigation />
        </div>
      </body>
    </html>
  );
}
